#!/bin/bash

echo "🚀 Meta Developer Setup for skinessentialsbyher.com"
echo "=================================================="
echo ""
echo "📋 Facebook App Configuration Update Required:"
echo ""
echo "1. Go to: https://developers.facebook.com/apps/764719166731391/facebook-login/settings/"
echo ""
echo "2. Update the following settings:"
echo "   ✅ Valid OAuth Redirect URIs:"
echo "      - https://skinessentialsbyher.com/api/auth/facebook"
echo "      - https://skinessentialsbyher.com/api/auth/facebook/callback"
echo ""
echo "3. Update App Domains:"
echo "   ✅ App Domains: skinessentialsbyher.com"
echo ""
echo "4. Update Site URL:"
echo "   ✅ Site URL: https://skinessentialsbyher.com"
echo ""
echo "📋 Instagram Basic Display API:"
echo "1. Go to: https://developers.facebook.com/apps/1121558939556493/instagram-basic-display/basic-display/"
echo ""
echo "2. Update the following settings:"
echo "   ✅ Valid OAuth Redirect URIs:"
echo "      - https://skinessentialsbyher.com/api/auth/instagram"
echo "      - https://skinessentialsbyher.com/api/auth/instagram/callback"
echo ""
echo "📋 Webhook Configuration (Facebook):"
echo "1. Go to: https://developers.facebook.com/apps/764719166731391/webhooks/"
echo ""
echo "2. Update Webhook URL:"
echo "   ✅ Callback URL: https://skinessentialsbyher.com/api/webhooks/facebook"
echo "   ✅ Verify Token: fb_webhook_2024_a7b3c9d2e8f1g4h5i6j7k8l9m0n1o2p3q4r5s6t7u8v9w0x1y2z3"
echo ""
echo "📋 Webhook Configuration (Instagram):"
echo "1. Go to: https://developers.facebook.com/apps/1121558939556493/webhooks/"
echo ""
echo "2. Update Webhook URL:"
echo "   ✅ Callback URL: https://skinessentialsbyher.com/api/webhooks/instagram"
echo "   ✅ Verify Token: ig_webhook_2024_z9y8x7w6v5u4t3s2r1q0p9o8n7m6l5k4j3i2h1g0f9e8d7c6b5a4"
echo ""
echo "🔧 App Review Requirements:"
echo "For production use, you'll need to submit for review:"
echo "   - pages_manage_posts"
echo "   - pages_read_engagement"
echo "   - instagram_basic"
echo "   - instagram_content_publish"
echo ""
echo "📱 Test Users (Optional):"
echo "You can add test users in App Roles > Roles > Test Users"
echo ""
echo "✅ After updating all settings, your Facebook and Instagram"
echo "   integration will work with your production domain!"
echo ""
echo "📝 Note: Make sure your website is deployed and accessible at"
echo "   https://skinessentialsbyher.com before testing the integration."